---
# tasks file for talkliketv
- name: Create user for talkliketv
  user:
    name: "{{ web_user }}"  # Username
    state: present  # Ensure the user is present
    createhome: no  # Create the user's home directory
    shell: /usr/sbin/nologin
    append: yes
  become: true

- name: Copy talkliketv binary to server
  copy:
    src: ~/
    dest: /etc/systemd/system/
    owner: "{{ web_user }}"
    group: "{{ web_user }}"
    mode: "744"

- name: Copy service file to server
  copy:
    src: ../../../remote/cloud/web.service
    dest: /etc/systemd/system/
    owner: "{{ web_user }}"
    group: "{{ web_user }}"
    mode: "664"

    echo "TALKLIKETV_DB_DSN='postgres://talkliketv:${DB_PASSWORD}@localhost/talkliketv'" >> /etc/environment
    echo "SMTP_PASSWORD=${SMTP_PASSWORD}" >> /etc/environment
    echo "SMTP_USERNAME=${SMTP_USERNAME}" >> /etc/environment