#- name: Add host to group 'talkliketv'
#  hosts: talkliketv
#  gather_facts: false
#  tasks:
#    - add_host:
#        name: '{{ new_host_ipaddr }}'
#        groups: talkliketv

- name: Install Postgres
  hosts: talkliketv
  become: True
  gather_facts: yes
  tags:
    - postgres
  roles:
    - role: postgres

- name: Install Caddy
  hosts: talkliketv
  become: True
  gather_facts: yes
  tags:
    - caddy
  roles:
    - role: caddy

- name: Install Talkliketv
  hosts: talkliketv
  become: True
  gather_facts: yes
  tags:
    - talkliketv
  roles:
    - role: talkliketv